### ISSUE TITLE
Deployment notifications aren't published to Slack if the PR title is too long to include the PR number

### ISSUE THREAD

**Issue by elipinska** [fac/serverless-tools#107]
Related to: https://freeagent.slack.com/archives/CJN0XULAU/p1678721458829869

If the PR title is too long, the PR number gets cut off from the title, causing `serverless-tools`' `notify` action to fail.

**Comment by HistoireDeBabar** [comment]
https://github.com/fac/internal-data-api/actions/runs/4850236488/jobs/8642961277

**Comment by elipinska** [comment]
Fixed in v0.14.0 of serverless-tools
