### ISSUE TITLE
Update Dockerfile to use a current version of Ruby

### ISSUE THREAD

**Issue by dgholz** [fac/serverless-tools#180]
At the moment, the Dockerfile is based off `ruby:2.7-slim-bullseye`. That's too old a version of Ruby to be supported by Mocha 2+, so whenever [a Dependabot PR comes around](https://github.com/fac/serverless-tools/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Fdependabot+%22Bump+mocha%22+%22to+2%22+) we (dev platform) need to remember to tell Dependabot to ignore the newer version of Mocha.

I previously [chatted to Paul about when Data Platform could update the image](https://github.com/fac/serverless-tools/pull/57#issuecomment-1490111261). Reflecting back on it, I don't understand how the version of Ruby in lambdas would affect this repository: the Docker image is only run from GitHub Actions?

Regardless, Ruby 2.7 end-of-lifed at the end of March, so Data Platform should move the image off it.

**Comment by HistoireDeBabar** [comment]
>  I don't understand how the version of Ruby in lambdas would affect this repository: the Docker image is only run from GitHub Actions?

The image builds zip file, which includes running `gem install` which will be installed to whichever directory/version of ruby is running. So if we bumped it up without updating the Lambda functions runtime, the gems wouldn't be available.

**Comment by HistoireDeBabar** [comment]
We're going to look into this when we have more capacity and move the ruby lambda functions to the latest AWS support

**Comment by HistoireDeBabar** [comment]
This was completed, we now use 3.2
