### ISSUE TITLE
Errors don't always stop Github Action execution.

### ISSUE THREAD

**Issue by HistoireDeBabar** [fac/serverless-tools#48]
There's an issue where the build step fails, but the Github Action continues, and as a result deploys a package that is not correctly bundled:

![Screenshot 2022-10-28 at 09 56 15](https://user-images.githubusercontent.com/6544057/198547600-b8a4bf83-5d0d-4832-b2a2-6dee3a2cf2d1.png)

Screenshot taken from https://github.com/fac/data-lake-management/actions/runs/3338364346/jobs/5525957230

The issue happened here as the poetry version in the code repo was changed, but serverless tools uses a different version. Ultimately, this left us with import errors at runtime.

**Comment by dancorne** [comment]
Some other instances where exceptions aren't raised:
 - [If an ECR tag can't be found it will try to update the code without `image_uri`](https://github.com/fac/serverless-tools/blob/main/lib/serverless-tools/deployer/function_deployer.rb#L47). Maybe should raise an exception [in the ECR pusher?](https://github.com/fac/serverless-tools/blob/main/lib/serverless-tools/deployer/ecr_pusher.rb#L20)
 - If you configure `functions.yml` with the wrong Lambda name, the error message is hidden [presumably by this line](https://github.com/fac/serverless-tools/blob/main/lib/serverless-tools/deployer/function_deployer.rb#L50)

**Comment by dancorne** [comment]
Just noticed this deprecation warning which looks relevant, ideally anything not successful would be non-zero:
```
Deprecation warning: Thor exit with status 0 on errors. To keep this behavior, you must define `exit_on_failure?` in `ServerlessTools::CLI`
```
